export const PRDUCT_LIST_REQUEST = "PRDUCT_LIST_REQUEST";
export const PRDUCT_LIST_SUCCESS = "PRDUCT_LIST_SUCCESS";
export const PRDUCT_LIST_FAIL = "PRDUCT_LIST_FAIL";

export const PRDUCT_DETAIL_REQUEST = "PRDUCT_DETAIL_REQUEST";
export const PRDUCT_DETAIL_SUCCESS = "PRDUCT_DETAIL_SUCCESS";
export const PRDUCT_DETAIL_FAIL = "PRDUCT_DETAIL_FAIL";
