export const Products = [
  {
    _id: 1,
    name: "Airpods max",
    image:
      "https://images.idgesg.net/images/article/2021/01/airpods-max-hero-100872392-large.jpg",
    description: "Apple Airpods max",
    brand: "Apple",
    category: "Electronics",
    price: 89.76,
    countInStock: 120,
    rating: 4.6,
    numReviews: 10,
  },
  {
    _id: 2,
    name: "Macbook Pro",
    image:
      "https://images.idgesg.net/images/article/2019/10/macbook-pro-2019-100815269-large.jpg",
    description: "Apple Mac max",
    brand: "Apple",
    category: "Electronics",
    price: 1189.76,
    countInStock: 12,
    rating: 4.5,
    numReviews: 47,
  },
  {
    _id: 3,
    name: "Airpods max",
    image:
      "https://images.idgesg.net/images/article/2021/01/airpods-max-hero-100872392-large.jpg",
    description: "Apple Airpods max",
    brand: "Apple",
    category: "Electronics",
    price: 89.76,
    countInStock: 120,
    rating: 3.5,
    numReviews: 35,
  },
  {
    _id: 4,
    name: "Macbook Pro",
    image:
      "https://images.idgesg.net/images/article/2019/10/macbook-pro-2019-100815269-large.jpg",
    description: "Apple Mac max",
    brand: "Apple",
    category: "Electronics",
    price: 1189.76,
    countInStock: 12,
    rating: 5.0,
    numReviews: 455,
  },
  {
    _id: 5,
    name: "Macbook Pro",
    image:
      "https://images.idgesg.net/images/article/2019/10/macbook-pro-2019-100815269-large.jpg",
    description: "Apple Mac max",
    brand: "Apple",
    category: "Electronics",
    price: 1189.76,
    countInStock: 12,
    rating: 5.0,
    numReviews: 0,
  },
];
